import React from 'react';
import { IconHome, IconCalendar } from '@arco-design/web-react/icon';

export const DirectoryList = [
  {
    rootId: 'A',
    title: '理念篇',
    parentId: -1,
    level: 0,
    children: [
      {
        rootId: 'A_a',
        title: '第一章 React理念',
        parentId: 'A',
        level: 1,
        children: [
          {
            rootId: 'A_a_1',
            title: '1.React理念',
            parentId: 'A_a',
            level: 2,
            children: [
              {
                rootId: 'A_a_1_1',
                title: 'React理念',
                parentId: 'A_a_1',
                level: 3,
              },
              {
                rootId: 'A_a_1_2',
                title: 'CPU的瓶颈',
                parentId: 'A_a_1',
                level: 3,
              },
              {
                rootId: 'A_a_1_3',
                title: 'IO的瓶颈',
                parentId: 'A_a_1',
                level: 3,
              },
              {
                rootId: 'A_a_1_4',
                title: '总结',
                parentId: 'A_a_1',
                level: 3,
              },
              {
                rootId: 'A_a_1_5',
                title: '参考资料',
                parentId: 'A_a_1',
                level: 3,
              },
            ],
          },
          {
            rootId: 'A_a_2',
            title: '2.老的react架构',
            parentId: 'A_a',
            level: 2,
            children: [
              {
                rootId: 'A_a_2_1',
                title: 'React15架构',
                parentId: 'A_a_2',
                level: 3,
              },
              {
                rootId: 'A_a_2_2',
                title: 'React15架构的缺点',
                parentId: 'A_a_2',
                level: 3,
              },
            ],
          },
          {
            rootId: 'A_a_3',
            title: '3.新的react架构',
            parentId: 'A_a',
            level: 2,
            children: [
              {
                rootId: 'A_a_3_1',
                title: 'React16架构',
                parentId: 'A_a_3',
                level: 3,
              },
              {
                rootId: 'A_a_3_2',
                title: '总结',
                parentId: 'A_a_3',
                level: 3,
              },
              {
                rootId: 'A_a_3_3',
                title: '参考资料',
                parentId: 'A_a_3',
                level: 3,
              },
            ],
          },
          {
            rootId: 'A_a_4',
            title: '4.Fiber架构的心智模型',
            parentId: 'A_a',
            level: 2,
            children: [
              {
                rootId: 'A_a_4_1',
                title: '什么是代数效应',
                parentId: 'A_a_4',
                level: 3,
              },
              {
                rootId: 'A_a_4_2',
                title: '代数效应在React中的应用',
                parentId: 'A_a_4',
                level: 3,
              },
              {
                rootId: 'A_a_4_3',
                title: '代数效应与Generator',
                parentId: 'A_a_4',
                level: 3,
              },
              {
                rootId: 'A_a_4_4',
                title: '代数效应与Fiber',
                parentId: 'A_a_4',
                level: 3,
              },
            ],
          },
          {
            rootId: 'A_a_5',
            title: '5.Fiber架构的实现原理',
            parentId: 'A_a',
            level: 2,
            children: [
              {
                rootId: 'A_a_5_1',
                title: 'Fiber的起源',
                parentId: 'A_a_5',
                level: 3,
              },
              {
                rootId: 'A_a_5_2',
                title: 'Fiber的含义',
                parentId: 'A_a_5',
                level: 3,
              },
              {
                rootId: 'A_a_5_3',
                title: 'Fiber的结构',
                parentId: 'A_a_5',
                level: 3,
              },
              {
                rootId: 'A_a_5_4',
                title: '总结',
                parentId: 'A_a_5',
                level: 3,
              },
              {
                rootId: 'A_a_5_5',
                title: '参考资料',
                parentId: 'A_a_5',
                level: 3,
              },
            ],
          },
          {
            rootId: 'A_a_6',
            title: '6.Fiber架构的工作原理',
            parentId: 'A_a',
            level: 2,
            children: [
              {
                rootId: 'A_a_6_1',
                title: '什么是“双缓存”',
                parentId: 'A_a_6',
                level: 3,
              },
              {
                rootId: 'A_a_6_2',
                title: '双缓存Fiber树',
                parentId: 'A_a_6',
                level: 3,
              },
              {
                rootId: 'A_a_6_3',
                title: 'mount时',
                parentId: 'A_a_6',
                level: 3,
              },
              {
                rootId: 'A_a_6_4',
                title: 'update时',
                parentId: 'A_a_6',
                level: 3,
              },
              {
                rootId: 'A_a_6_5',
                title: '总结',
                parentId: 'A_a_6',
                level: 3,
              },
              {
                rootId: 'A_a_6_6',
                title: '参考资料',
                parentId: 'A_a_6',
                level: 3,
              },
            ],
          },
          {
            rootId: 'A_a_7',
            title: '总结',
            parentId: 'A_a',
            level: 2,
          },
        ],
      },
      {
        rootId: 'A_b',
        title: '第二章 前置知识',
        parentId: 'A',
        level: 1,
        children: [
          {
            rootId: 'A_b_1',
            title: '1.源码的文件结构',
            parentId: 'A_b',
            level: 2,
            children: [
              {
                rootId: 'A_b_1_1',
                title: '顶层目录',
                parentId: 'A_b_1',
                level: 3,
              },
              {
                rootId: 'A_b_1_2',
                title: 'packages目录',
                parentId: 'A_b_1',
                level: 3,
              },
            ],
          },
          {
            rootId: 'A_b_2',
            title: '2.调试源码',
            parentId: 'A_b',
            level: 2,
            children: [
              {
                rootId: 'A_b_2_1',
                title: '拉取源码',
                parentId: 'A_b_2',
                level: 3,
              },
              {
                rootId: 'A_b_2_2',
                title: '创建项目',
                parentId: 'A_b_2',
                level: 3,
              },
            ],
          },
          {
            rootId: 'A_b_3',
            title: '3.深入理解JSX',
            parentId: 'A_b',
            level: 2,
            children: [
              {
                rootId: 'A_b_3_1',
                title: 'JSX简介',
                parentId: 'A_b_3',
                level: 3,
              },
              {
                rootId: 'A_b_3_2',
                title: 'React.createElement',
                parentId: 'A_b_3',
                level: 3,
              },
              {
                rootId: 'A_b_3_3',
                title: 'React Component',
                parentId: 'A_b_3',
                level: 3,
              },
              {
                rootId: 'A_b_3_3',
                title: 'JSX与Fiber节点',
                parentId: 'A_b_3',
                level: 3,
              },
              {
                rootId: 'A_b_3_4',
                title: '参考资料',
                parentId: 'A_b_3',
                level: 3,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    rootId: 'B',
    title: '架构篇',
    parentId: -1,
    level: 0,
    children: [
      {
        rootId: 'B_a',
        title: '第三章 render阶段',
        parentId: 'B',
        level: 1,
        children: [
          {
            rootId: 'B_a_1',
            title: '1.流程概览',
            parentId: 'B_a',
            level: 2,
            children: [
              {
                rootId: 'B_a_1_1',
                title: '“递”阶段',
                parentId: 'B_a_1',
                level: 3,
              },
              {
                rootId: 'B_a_1_2',
                title: '“归”阶段',
                parentId: 'B_a_1',
                level: 3,
              },
              {
                rootId: 'B_a_1_3',
                title: '例子',
                parentId: 'B_a_1',
                level: 3,
              },
              {
                rootId: 'B_a_1_4',
                title: '总结',
                parentId: 'B_a_1',
                level: 3,
              },
              {
                rootId: 'B_a_1_5',
                title: '参考资料',
                parentId: 'B_a_1',
                level: 3,
              },
            ],
          },
          {
            rootId: 'B_a_2',
            title: '2.beginWork',
            parentId: 'B_a',
            level: 2,
            children: [
              {
                rootId: 'B_a_2_1',
                title: '方法概览',
                parentId: 'B_a_2',
                level: 3,
              },
              {
                rootId: 'B_a_2_2',
                title: 'update时',
                parentId: 'B_a_2',
                level: 3,
              },
              {
                rootId: 'B_a_2_3',
                title: 'mount时',
                parentId: 'B_a_2',
                level: 3,
              },
              {
                rootId: 'B_a_2_4',
                title: 'reconcileChildren',
                parentId: 'B_a_2',
                level: 3,
              },
              {
                rootId: 'B_a_2_5',
                title: 'effectTag',
                parentId: 'B_a_2',
                level: 3,
              },
              {
                rootId: 'B_a_2_6',
                title: '参考资料',
                parentId: 'B_a_2',
                level: 3,
              },
            ],
          },
          {
            rootId: 'B_a_3',
            title: '3.completeWork',
            parentId: 'B_a',
            level: 2,
            children: [
              {
                rootId: 'B_a_3_1',
                title: '流程概览',
                parentId: 'B_a_3',
                level: 3,
              },
              {
                rootId: 'B_a_3_2',
                title: '处理HostComponent',
                parentId: 'B_a_3',
                level: 3,
              },
              {
                rootId: 'B_a_3_3',
                title: 'update时',
                parentId: 'B_a_3',
                level: 3,
              },
              {
                rootId: 'B_a_3_4',
                title: 'mount时',
                parentId: 'B_a_3',
                level: 3,
              },
              {
                rootId: 'B_a_3_5',
                title: 'effectList',
                parentId: 'B_a_3',
                level: 3,
              },
              {
                rootId: 'B_a_3_6',
                title: '流程结尾',
                parentId: 'B_a_3',
                level: 3,
              },
              {
                rootId: 'B_a_3_7',
                title: '参考资料',
                parentId: 'B_a_3',
                level: 3,
              },
            ],
          },
        ],
      },
      {
        rootId: 'B_b',
        title: '第四章 commit阶段',
        parentId: 'B',
        level: 1,
        children: [
          {
            rootId: 'B_b_1',
            title: '1.流程概览',
            parentId: 'B_b',
            level: 2,
            children: [
              {
                rootId: 'B_b_1_1',
                title: 'before mutation之前',
                parentId: 'B_b_1',
                level: 3,
              },
              {
                rootId: 'B_b_1_2',
                title: 'layout之后',
                parentId: 'B_b_1',
                level: 3,
              },
            ],
          },
          {
            rootId: 'B_b_2',
            title: '2.before mutation阶段',
            parentId: 'B_b',
            level: 2,
            children: [
              {
                rootId: 'B_b_2_1',
                title: '概览',
                parentId: 'B_b_2',
                level: 3,
              },
              {
                rootId: 'B_b_2_2',
                title: 'commitBeforeMutationEffects',
                parentId: 'B_b_2',
                level: 3,
              },
              {
                rootId: 'B_b_2_3',
                title: '调用getSnapshotBeforeUpdate',
                parentId: 'B_b_2',
                level: 3,
              },
              {
                rootId: 'B_b_2_4',
                title: '调度useEffect',
                parentId: 'B_b_2',
                level: 3,
              },
              {
                rootId: 'B_b_2_5',
                title: '总结',
                parentId: 'B_b_2',
                level: 3,
              },
            ],
          },
          {
            rootId: 'B_b_3',
            title: '3.mutation阶段',
            parentId: 'B_b',
            level: 2,
            children: [
              {
                rootId: 'B_b_3_1',
                title: '概览',
                parentId: 'B_b_3',
                level: 3,
              },
              {
                rootId: 'B_b_3_2',
                title: 'commitMutationEffects',
                parentId: 'B_b_3',
                level: 3,
              },
              {
                rootId: 'B_b_3_3',
                title: 'Placement effect',
                parentId: 'B_b_3',
                level: 3,
              },
              {
                rootId: 'B_b_3_4',
                title: 'Update effect',
                parentId: 'B_b_3',
                level: 3,
              },
              {
                rootId: 'B_b_3_5',
                title: 'Deletion effect',
                parentId: 'B_b_3',
                level: 3,
              },
              {
                rootId: 'B_b_3_6',
                title: '总结',
                parentId: 'B_b_3',
                level: 3,
              },
            ],
          },
          {
            rootId: 'B_b_4',
            title: '4.layout阶段',
            parentId: 'B_b',
            level: 2,
            children: [
              {
                rootId: 'B_b_4_1',
                title: '概览',
                parentId: 'B_b_4',
                level: 3,
              },
              {
                rootId: 'B_b_4_2',
                title: 'commitLayoutEffects',
                parentId: 'B_b_4',
                level: 3,
              },
              {
                rootId: 'B_b_4_3',
                title: 'commitLayoutEffectOnFiber',
                parentId: 'B_b_4',
                level: 3,
              },
              {
                rootId: 'B_b_4_4',
                title: 'commitAttachRef',
                parentId: 'B_b_4',
                level: 3,
              },
              {
                rootId: 'B_b_4_5',
                title: 'current Fiber树切换',
                parentId: 'B_b_4',
                level: 3,
              },
              {
                rootId: 'B_b_4_6',
                title: '总结',
                parentId: 'B_b_4',
                level: 3,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    rootId: 'C',
    title: '实现篇',
    parentId: -1,
    level: 0,
    children: [
      {
        rootId: 'C_a',
        title: '第五章 diff算法',
        parentId: 'C',
        level: 1,
        children: [
          {
            rootId: 'C_a_1',
            title: '1.概览',
            parentId: 'C_a',
            level: 2,
            children: [
              {
                rootId: 'C_a_1_1',
                title: 'Diff的瓶颈以及React如何应对',
                parentId: 'C_a_1',
                level: 3,
              },
              {
                rootId: 'C_a_1_2',
                title: 'Diff是如何实现的',
                parentId: 'C_a_1',
                level: 3,
              },
            ],
          },
          {
            rootId: 'C_a_2',
            title: '2.单节点Diff',
            parentId: 'C_a',
            level: 2,
            children: [
              {
                rootId: 'C_a_2_1',
                title: '练习题',
                parentId: 'C_a_2',
                level: 3,
              },
            ],
          },
          {
            rootId: 'C_a_3',
            title: '3.多节点Diff',
            parentId: 'C_a',
            level: 2,
            children: [
              {
                rootId: 'C_a_3_1',
                title: '概览',
                parentId: 'C_a_3',
                level: 3,
              },
              {
                rootId: 'C_a_3_2',
                title: 'Diff的思路',
                parentId: 'C_a_3',
                level: 3,
              },
              {
                rootId: 'C_a_3_3',
                title: '第一轮遍历',
                parentId: 'C_a_3',
                level: 3,
              },
              {
                rootId: 'C_a_3_4',
                title: '第二轮遍历',
                parentId: 'C_a_3',
                level: 3,
              },
              {
                rootId: 'C_a_3_5',
                title: '处理移动的节点',
                parentId: 'C_a_3',
                level: 3,
              },
              {
                rootId: 'C_a_3_6',
                title: '标记节点是否移动',
                parentId: 'C_a_3',
                level: 3,
              },
              {
                rootId: 'C_a_3_7',
                title: 'Demo1',
                parentId: 'C_a_3',
                level: 3,
              },
              {
                rootId: 'C_a_3_8',
                title: 'Demo2',
                parentId: 'C_a_3',
                level: 3,
              },
            ],
          },
        ],
      },
      {
        rootId: 'C_b',
        title: '第六章 状态更新',
        parentId: 'C',
        level: 1,
        children: [
          {
            rootId: 'C_b_1',
            title: '1.流程概览',
            parentId: 'C_b',
            level: 2,
            children: [
              {
                rootId: 'C_b_1_1',
                title: '几个关键节点',
                parentId: 'C_b_1',
                level: 3,
              },
              {
                rootId: 'C_b_1_2',
                title: '总结',
                parentId: 'C_b_1',
                level: 3,
              },
              {
                rootId: 'C_b_1_3',
                title: '总结',
                parentId: 'C_b_1',
                level: 3,
              },
            ],
          },
          {
            rootId: 'C_b_2',
            title: '2.心智模式',
            parentId: 'C_b',
            level: 2,
            children: [
              {
                rootId: 'C_b_2_1',
                title: '同步更新的React',
                parentId: 'C_b_2',
                level: 3,
              },
              {
                rootId: 'C_b_2_2',
                title: '并发更新的React',
                parentId: 'C_b_2',
                level: 3,
              },
              {
                rootId: 'C_b_2_3',
                title: '参考资料',
                parentId: 'C_b_2',
                level: 3,
              },
            ],
          },
          {
            rootId: 'C_b_3',
            title: '3.Update',
            parentId: 'C_b',
            level: 2,
            children: [
              {
                rootId: 'C_b_3_1',
                title: 'Update的分类',
                parentId: 'C_b_3',
                level: 3,
              },
              {
                rootId: 'C_b_3_2',
                title: 'Update的结构',
                parentId: 'C_b_3',
                level: 3,
              },
              {
                rootId: 'C_b_3_3',
                title: 'Update与Fiber的联系',
                parentId: 'C_b_3',
                level: 3,
              },
              {
                rootId: 'C_b_3_4',
                title: 'updateQueue',
                parentId: 'C_b_3',
                level: 3,
              },
              {
                rootId: 'C_b_3_5',
                title: '例子',
                parentId: 'C_b_3',
                level: 3,
              },
            ],
          },
          {
            rootId: 'C_b_4',
            title: '4.深入理解优先级',
            parentId: 'C_b',
            level: 2,
            children: [
              {
                rootId: 'C_b_4_1',
                title: '什么是优先级',
                parentId: 'C_b_4',
                level: 3,
              },
              {
                rootId: 'C_b_4_2',
                title: '如何调度优先级',
                parentId: 'C_b_4',
                level: 3,
              },
              {
                rootId: 'C_b_4_3',
                title: '例子',
                parentId: 'C_b_4',
                level: 3,
              },
              {
                rootId: 'C_b_4_4',
                title: '如何保证状态正确',
                parentId: 'C_b_4',
                level: 3,
              },
              {
                rootId: 'C_b_4_5',
                title: '参考资料',
                parentId: 'C_b_4',
                level: 3,
              },
            ],
          },
          {
            rootId: 'C_b_5',
            title: '5.ReactDOM.render',
            parentId: 'C_b',
            level: 2,
            children: [
              {
                rootId: 'C_b_5_1',
                title: '创建fiber',
                parentId: 'C_b_5',
                level: 3,
              },
              {
                rootId: 'C_b_5_2',
                title: '创建update',
                parentId: 'C_b_5',
                level: 3,
              },
              {
                rootId: 'C_b_5_3',
                title: '流程概览',
                parentId: 'C_b_5',
                level: 3,
              },
              {
                rootId: 'C_b_5_4',
                title: 'React的其他入口函数',
                parentId: 'C_b_5',
                level: 3,
              },
            ],
          },
          {
            rootId: 'C_b_6',
            title: '6.this.setState',
            parentId: 'C_b',
            level: 2,
            children: [
              {
                rootId: 'C_b_6_1',
                title: '流程概览',
                parentId: 'C_b_6',
                level: 3,
              },
              {
                rootId: 'C_b_6_2',
                title: 'this.forceUpdate',
                parentId: 'C_b_6',
                level: 3,
              },
              {
                rootId: 'C_b_6_3',
                title: '总结',
                parentId: 'C_b_6',
                level: 3,
              },
            ],
          },
        ],
      },
      {
        rootId: 'C_c',
        title: '第七章 Hooks',
        parentId: 'C',
        level: 1,
        children: [
          {
            rootId: 'C_c_1',
            title: '1.Hooks理念',
            parentId: 'C_c',
            level: 2,
            children: [
              {
                rootId: 'C_c_1_1',
                title: '从LOGO聊起',
                parentId: 'C_c_1',
                level: 3,
              },
              {
                rootId: 'C_c_1_2',
                title: '总结',
                parentId: 'C_c_1',
                level: 3,
              },
            ],
          },
          {
            rootId: 'C_c_2',
            title: '2.极简Hooks实现',
            parentId: 'C_c',
            level: 2,
            children: [
              {
                rootId: 'C_c_2_1',
                title: '工作原理',
                parentId: 'C_c_2',
                level: 3,
              },
              {
                rootId: 'C_c_2_2',
                title: '更新是什么',
                parentId: 'C_c_2',
                level: 3,
              },
              {
                rootId: 'C_c_2_3',
                title: 'update数据结构',
                parentId: 'C_c_2',
                level: 3,
              },
              {
                rootId: 'C_c_2_4',
                title: '状态如何保存',
                parentId: 'C_c_2',
                level: 3,
              },
              {
                rootId: 'C_c_2_5',
                title: 'Hook数据结构',
                parentId: 'C_c_2',
                level: 3,
              },
              {
                rootId: 'C_c_2_6',
                title: '模拟React调度更新流程',
                parentId: 'C_c_2',
                level: 3,
              },
              {
                rootId: 'C_c_2_7',
                title: '计算state',
                parentId: 'C_c_2',
                level: 3,
              },
              {
                rootId: 'C_c_2_8',
                title: '对触发事件进行抽象',
                parentId: 'C_c_2',
                level: 3,
              },
              {
                rootId: 'C_c_2_9',
                title: '在线Demo',
                parentId: 'C_c_2',
                level: 3,
              },
              {
                rootId: 'C_c_2_10',
                title: '与React的区别',
                parentId: 'C_c_2',
                level: 3,
              },
            ],
          },
          {
            rootId: 'C_c_3',
            title: '3.Hooks数据结构',
            parentId: 'C_c',
            level: 2,
            children: [
              {
                rootId: 'C_c_3_1',
                title: 'dispatcher',
                parentId: 'C_c_3',
                level: 3,
              },
              {
                rootId: 'C_c_3_2',
                title: '一个dispatcher使用场景',
                parentId: 'C_c_3',
                level: 3,
              },
              {
                rootId: 'C_c_3_3',
                title: 'Hook的数据结构',
                parentId: 'C_c_3',
                level: 3,
              },
              {
                rootId: 'C_c_3_4',
                title: 'memoizedState',
                parentId: 'C_c_3',
                level: 3,
              },
            ],
          },
          {
            rootId: 'C_c_4',
            title: '4.useState与useReducer',
            parentId: 'C_c',
            level: 2,
            children: [
              {
                rootId: 'C_c_4_1',
                title: '流程概览',
                parentId: 'C_c_4',
                level: 3,
              },
              {
                rootId: 'C_c_4_2',
                title: '声明阶段',
                parentId: 'C_c_4',
                level: 3,
              },
              {
                rootId: 'C_c_4_3',
                title: '调用阶段',
                parentId: 'C_c_4',
                level: 3,
              },
              {
                rootId: 'C_c_4_4',
                title: '小Tip',
                parentId: 'C_c_4',
                level: 3,
              },
            ],
          },
          {
            rootId: 'C_c_5',
            title: '5.useEffect',
            parentId: 'C_c',
            level: 2,
            children: [
              {
                rootId: 'C_c_5_1',
                title: 'flushPassiveEffectsImpl',
                parentId: 'C_c_5',
                level: 3,
              },
              {
                rootId: 'C_c_5_2',
                title: '阶段一：销毁函数的执行',
                parentId: 'C_c_5',
                level: 3,
              },
              {
                rootId: 'C_c_5_3',
                title: '阶段二：回调函数的执行',
                parentId: 'C_c_5',
                level: 3,
              },
            ],
          },
          {
            rootId: 'C_c_6',
            title: '6.useRef',
            parentId: 'C_c',
            level: 2,
            children: [
              {
                rootId: 'C_c_6_1',
                title: 'useRef',
                parentId: 'C_c_6',
                level: 3,
              },
              {
                rootId: 'C_c_6_2',
                title: 'ref的工作流程',
                parentId: 'C_c_6',
                level: 3,
              },
              {
                rootId: 'C_c_6_3',
                title: 'render阶段',
                parentId: 'C_c_6',
                level: 3,
              },
              {
                rootId: 'C_c_6_4',
                title: 'commit阶段',
                parentId: 'C_c_6',
                level: 3,
              },
              {
                rootId: 'C_c_6_5',
                title: '总结',
                parentId: 'C_c_6',
                level: 3,
              },
            ],
          },
          {
            rootId: 'C_c_7',
            title: '7.useMemo与useCallback',
            parentId: 'C_c',
            level: 2,
            children: [
              {
                rootId: 'C_c_7_1',
                title: 'mount',
                parentId: 'C_c_7',
                level: 3,
              },
              {
                rootId: 'C_c_7_2',
                title: 'update',
                parentId: 'C_c_7',
                level: 3,
              },
            ],
          },
        ],
      },
      {
        rootId: 'C_d',
        title: '第八章 Concurrent Mode',
        parentId: 'C',
        level: 1,
        children: [
          {
            rootId: 'C_d_1',
            title: '1.概览',
            parentId: 'C_d',
            level: 2,
            children: [
              {
                rootId: 'C_d_1_1',
                title: '底层架构 —— Fiber架构',
                parentId: 'C_d_1',
                level: 3,
              },
              {
                rootId: 'C_d_1_2',
                title: '架构的驱动力 —— Scheduler',
                parentId: 'C_d_1',
                level: 3,
              },
              {
                rootId: 'C_d_1_3',
                title: '架构运行策略 —— lane模型',
                parentId: 'C_d_1',
                level: 3,
              },
              {
                rootId: 'C_d_1_4',
                title: '上层实现',
                parentId: 'C_d_1',
                level: 3,
              },
              {
                rootId: 'C_d_1_5',
                title: '总结',
                parentId: 'C_d_1',
                level: 3,
              },
            ],
          },
          {
            rootId: 'C_d_2',
            title: '2.Scheduler的原理与实现',
            parentId: 'C_d',
            level: 2,
            children: [
              {
                rootId: 'C_d_2_1',
                title: '时间切片原理',
                parentId: 'C_d_2',
                level: 3,
              },
              {
                rootId: 'C_d_2_2',
                title: '优先级调度',
                parentId: 'C_d_2',
                level: 3,
              },
              {
                rootId: 'C_d_2_3',
                title: '优先级的意义',
                parentId: 'C_d_2',
                level: 3,
              },
              {
                rootId: 'C_d_2_4',
                title: '不同优先级任务的排序',
                parentId: 'C_d_2',
                level: 3,
              },
              {
                rootId: 'C_d_2_5',
                title: '总结',
                parentId: 'C_d_2',
                level: 3,
              },
            ],
          },
          {
            rootId: 'C_d_3',
            title: '3.lane模型',
            parentId: 'C_d',
            level: 2,
            children: [
              {
                rootId: 'C_d_3_1',
                title: '表示优先级的不同',
                parentId: 'C_d_3',
                level: 3,
              },
              {
                rootId: 'C_d_3_2',
                title: '表示“批”的概念',
                parentId: 'C_d_3',
                level: 3,
              },
              {
                rootId: 'C_d_3_3',
                title: '方便进行优先级相关计算',
                parentId: 'C_d_3',
                level: 3,
              },
              {
                rootId: 'C_d_3_4',
                title: '总结',
                parentId: 'C_d_3',
                level: 3,
              },
            ],
          },
          {
            rootId: 'C_d_4',
            title: '4.异步可中断更新',
            parentId: 'C_d',
            level: 2,
            children: [],
          },
        ],
      },
    ],
  },
];

export const DirectoryLevelIcon = {
  0: <IconHome />,
  1: <IconCalendar />,
  2: null,
  3: null,
};
